### ISSUE TITLE
sbt build error

### ISSUE THREAD

**Issue by nhat416** [jgperrin/net.jgp.books.spark.ch03#11]
hi @rambabu-posa I am getting the following error after I cd into the directory and run `sbt clean assembly`:
> [info] [launcher] getting org.scala-sbt sbt 1.0.3  (this may take some time)...
downloading https://repo1.maven.org/maven2/org/scala-sbt/command_2.12/1.0.3/command_2.12-1.0.3.jar ...
downloading https://repo1.maven.org/maven2/org/scala-sbt/run_2.12/1.0.3/run_2.12-1.0.3.jar ...
downloading https://repo1.maven.org/maven2/org/scala-sbt/logic_2.12/1.0.3/logic_2.12-1.0.3.jar ...
downloading https://repo1.maven.org/maven2/org/scala-sbt/main-settings_2.12/1.0.3/main-settings_2.12-1.0.3.jar ...
downloading https://repo1.maven.org/maven2/org/scala-sbt/main_2.12/1.0.3/main_2.12-1.0.3.jar ...
downloading https://repo1.maven.org/maven2/org/scala-sbt/actions_2.12/1.0.3/actions_2.12-1.0.3.jar ...
downloading https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.0.3/sbt-1.0.3.jar ...
:: loading settings :: url = jar:file:/Users/nhattran/.sdkman/candidates/sbt/1.4.6/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
:: loading settings :: url = jar:file:/Users/nhattran/.sdkman/candidates/sbt/1.4.6/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
:: loading settings :: url = jar:file:/Users/nhattran/.sdkman/candidates/sbt/1.4.6/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
:: loading settings :: url = jar:file:/Users/nhattran/.sdkman/candidates/sbt/1.4.6/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
:: loading settings :: url = jar:file:/Users/nhattran/.sdkman/candidates/sbt/1.4.6/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
:: loading settings :: url = jar:file:/Users/nhattran/.sdkman/candidates/sbt/1.4.6/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
:: loading settings :: url = jar:file:/Users/nhattran/.sdkman/candidates/sbt/1.4.6/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
:: loading settings :: url = jar:file:/Users/nhattran/.sdkman/candidates/sbt/1.4.6/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
downloading https://repo1.maven.org/maven2/org/scala-sbt/collections_2.12/1.0.3/collections_2.12-1.0.3.jar ...
        [SUCCESSFUL ] org.scala-sbt#logic_2.12;1.0.3!logic_2.12.jar (511ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/launcher-interface/1.0.0/launcher-interface-1.0.0.jar ...
        [SUCCESSFUL ] org.scala-sbt#launcher-interface;1.0.0!launcher-interface.jar (181ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/io_2.12/1.0.2/io_2.12-1.0.2.jar ...
        [SUCCESSFUL ] org.scala-sbt#sbt;1.0.3!sbt.jar (947ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-logging_2.12/1.0.2/util-logging_2.12-1.0.2.jar ...
        [SUCCESSFUL ] org.scala-sbt#run_2.12;1.0.3!run_2.12.jar (973ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/librarymanagement-core_2.12/1.0.3/librarymanagement-core_2.12-1.0.3.jar ...
        [SUCCESSFUL ] org.scala-sbt#io_2.12;1.0.2!io_2.12.jar (411ms)
        [SUCCESSFUL ] org.scala-sbt#actions_2.12;1.0.3!actions_2.12.jar (1131ms)
        [SUCCESSFUL ] org.scala-sbt#command_2.12;1.0.3!command_2.12.jar (1130ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/librarymanagement-ivy_2.12/1.0.3/librarymanagement-ivy_2.12-1.0.3.jar ...
downloading https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.0.3/compiler-interface-1.0.3.jar ...
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-compile_2.12/1.0.3/zinc-compile_2.12-1.0.3.jar ...
        [SUCCESSFUL ] org.scala-sbt#main-settings_2.12;1.0.3!main-settings_2.12.jar (1195ms)
        [SUCCESSFUL ] org.scala-sbt#collections_2.12;1.0.3!collections_2.12.jar (890ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-relation_2.12/1.0.2/util-relation_2.12-1.0.2.jar ...
downloading https://repo1.maven.org/maven2/com/eed3si9n/sjson-new-scalajson_2.12/0.8.0/sjson-new-scalajson_2.12-0.8.0.jar ...
        [SUCCESSFUL ] org.scala-sbt#util-logging_2.12;1.0.2!util-logging_2.12.jar (331ms)
        [SUCCESSFUL ] org.scala-sbt#zinc-compile_2.12;1.0.3!zinc-compile_2.12.jar (143ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-position_2.12/1.0.2/util-position_2.12-1.0.2.jar ...
downloading https://repo1.maven.org/maven2/com/eed3si9n/sjson-new-core_2.12/0.8.0/sjson-new-core_2.12-0.8.0.jar ...
        [SUCCESSFUL ] org.scala-sbt#compiler-interface;1.0.3!compiler-interface.jar (174ms)
        [SUCCESSFUL ] org.scala-sbt#util-relation_2.12;1.0.2!util-relation_2.12.jar (123ms)
        [SUCCESSFUL ] com.eed3si9n#sjson-new-scalajson_2.12;0.8.0!sjson-new-scalajson_2.12.jar (123ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/completion_2.12/1.0.3/completion_2.12-1.0.3.jar ...
downloading https://repo1.maven.org/maven2/org/scala-sbt/task-system_2.12/1.0.3/task-system_2.12-1.0.3.jar ...
downloading https://repo1.maven.org/maven2/org/scala-sbt/tasks_2.12/1.0.3/tasks_2.12-1.0.3.jar ...
        [SUCCESSFUL ] org.scala-sbt#util-position_2.12;1.0.2!util-position_2.12.jar (157ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/testing_2.12/1.0.3/testing_2.12-1.0.3.jar ...
        [SUCCESSFUL ] org.scala-sbt#librarymanagement-core_2.12;1.0.3!librarymanagement-core_2.12.jar (505ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-tracking_2.12/1.0.2/util-tracking_2.12-1.0.2.jar ...
        [SUCCESSFUL ] org.scala-sbt#tasks_2.12;1.0.3!tasks_2.12.jar (179ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-classpath_2.12/1.0.3/zinc-classpath_2.12-1.0.3.jar ...
        [SUCCESSFUL ] org.scala-sbt#task-system_2.12;1.0.3!task-system_2.12.jar (224ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-apiinfo_2.12/1.0.3/zinc-apiinfo_2.12-1.0.3.jar ...
        [SUCCESSFUL ] org.scala-sbt#librarymanagement-ivy_2.12;1.0.3!librarymanagement-ivy_2.12.jar (404ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-ivy-integration_2.12/1.0.3/zinc-ivy-integration_2.12-1.0.3.jar ...
        [SUCCESSFUL ] org.scala-sbt#util-tracking_2.12;1.0.2!util-tracking_2.12.jar (104ms)
        [SUCCESSFUL ] org.scala-sbt#completion_2.12;1.0.3!completion_2.12.jar (266ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc_2.12/1.0.3/zinc_2.12-1.0.3.jar ...
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-control_2.12/1.0.2/util-control_2.12-1.0.2.jar ...
        [SUCCESSFUL ] org.scala-sbt#main_2.12;1.0.3!main_2.12.jar (1641ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.0.2/util-interface-1.0.2.jar ...
        [SUCCESSFUL ] org.scala-sbt#zinc-classpath_2.12;1.0.3!zinc-classpath_2.12.jar (156ms)
        [SUCCESSFUL ] org.scala-sbt#testing_2.12;1.0.3!testing_2.12.jar (208ms)
downloading https://repo1.maven.org/maven2/com/eed3si9n/sjson-new-murmurhash_2.12/0.8.0/sjson-new-murmurhash_2.12-0.8.0.jar ...
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-cache_2.12/1.0.2/util-cache_2.12-1.0.2.jar ...
        [SUCCESSFUL ] org.scala-sbt#zinc-ivy-integration_2.12;1.0.3!zinc-ivy-integration_2.12.jar (128ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/test-agent/1.0.3/test-agent-1.0.3.jar ...
        [SUCCESSFUL ] org.scala-sbt#util-control_2.12;1.0.2!util-control_2.12.jar (116ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-classfile_2.12/1.0.3/zinc-classfile_2.12-1.0.3.jar ...
        [SUCCESSFUL ] org.scala-sbt#zinc_2.12;1.0.3!zinc_2.12.jar (145ms)
        [SUCCESSFUL ] org.scala-sbt#zinc-apiinfo_2.12;1.0.3!zinc-apiinfo_2.12.jar (193ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-compile-core_2.12/1.0.3/zinc-compile-core_2.12-1.0.3.jar ...
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-core_2.12/1.0.3/zinc-core_2.12-1.0.3.jar ...
        [SUCCESSFUL ] org.scala-sbt#util-interface;1.0.2!util-interface.jar (111ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-persist_2.12/1.0.3/zinc-persist_2.12-1.0.3.jar ...
        [SUCCESSFUL ] com.eed3si9n#sjson-new-murmurhash_2.12;0.8.0!sjson-new-murmurhash_2.12.jar (105ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/core-macros_2.12/1.0.3/core-macros_2.12-1.0.3.jar ...
        [SUCCESSFUL ] org.scala-sbt#test-agent;1.0.3!test-agent.jar (132ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/protocol_2.12/1.0.3/protocol_2.12-1.0.3.jar ...
        [SUCCESSFUL ] org.scala-sbt#util-cache_2.12;1.0.2!util-cache_2.12.jar (167ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/ivy/ivy/2.3.0-sbt-1b57d3bbc08ecf671169fd548918da18c91f77be/ivy-2.3.0-sbt-1b57d3bbc08ecf671169fd548918da18c91f77be.jar ...
        [SUCCESSFUL ] org.scala-sbt#zinc-classfile_2.12;1.0.3!zinc-classfile_2.12.jar (163ms)
        [SUCCESSFUL ] org.scala-sbt#core-macros_2.12;1.0.3!core-macros_2.12.jar (167ms)
        [SUCCESSFUL ] org.scala-sbt#zinc-compile-core_2.12;1.0.3!zinc-compile-core_2.12.jar (214ms)
        [SUCCESSFUL ] org.scala-sbt#zinc-core_2.12;1.0.3!zinc-core_2.12.jar (232ms)
        [SUCCESSFUL ] com.eed3si9n#sjson-new-core_2.12;0.8.0!sjson-new-core_2.12.jar (703ms)
        [SUCCESSFUL ] org.scala-sbt#protocol_2.12;1.0.3!protocol_2.12.jar (210ms)
        [SUCCESSFUL ] org.scala-sbt.ivy#ivy;2.3.0-sbt-1b57d3bbc08ecf671169fd548918da18c91f77be!ivy.jar (487ms)
        [SUCCESSFUL ] org.scala-sbt#zinc-persist_2.12;1.0.3!zinc-persist_2.12.jar (727ms)
:: retrieving :: org.scala-sbt#boot-app
        confs: [default]
        69 artifacts copied, 0 already retrieved
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /Users/nhattran/projects/spark-in-action/net.jgp.books.spark.ch03/project
[info] Updating {file:/Users/nhattran/projects/spark-in-action/net.jgp.books.spark.ch03/project/}net-jgp-books-spark-ch03-build...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.eed3si9n#sbt-assembly;0.14.10: Resolution failed several times for dependency: com.eed3si9n#sbt-assembly;0.14.10 {compile=[default(compile)]}:: 
[warn]  Index 1 out of bounds for length 1
[warn]  Index 1 out of bounds for length 1
[warn]  Index 1 out of bounds for length 1
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          com.eed3si9n:sbt-assembly:0.14.10 (scalaVersion=2.12, sbtVersion=1.0)
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]          com.eed3si9n:sbt-assembly:0.14.10 (scalaVersion=2.12, sbtVersion=1.0) (/Users/nhattran/projects/spark-in-action/net.jgp.books.spark.ch03/project/plugins.sbt#L1-2)
[warn]            +- default:net-jgp-books-spark-ch03-build:0.1-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.eed3si9n#sbt-assembly;0.14.10: Resolution failed several times for dependency: com.eed3si9n#sbt-assembly;0.14.10 {compile=[default(compile)]}:: 
[error]         Index 1 out of bounds for length 1
[error]         Index 1 out of bounds for length 1
[error]         Index 1 out of bounds for length 1
[error] 
[error]         at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:331)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:205)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:229)
[error]         at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:190)
[error]         at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error]         at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error]         at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error]         at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error]         at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error]         at xsbt.boot.Using$.withResource(Using.scala:10)
[error]         at xsbt.boot.Using$.apply(Using.scala:9)
[error]         at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error]         at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error]         at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error]         at xsbt.boot.Locks$.apply(Locks.scala:28)
[error]         at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:185)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:182)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:228)
[error]         at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:190)
[error]         at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:38)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:91)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:104)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:104)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:87)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:118)
[error]         at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2353)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:64)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:266)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:829)
[error] (*:update) sbt.librarymanagement.ResolveException: unresolved dependency: com.eed3si9n#sbt-assembly;0.14.10: Resolution failed several times for dependency: com.eed3si9n#sbt-assembly;0.14.10 {compile=[default(compile)]}:: 
[error]         Index 1 out of bounds for length 1
[error]         Index 1 out of bounds for length 1
[error]         Index 1 out of bounds for length 1
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
>
Any help is appreciated thank you.

**Comment by rambabu-posa** [comment]
@nhat416 Sure, let me check it.

**Comment by jgperrin** [comment]
@rambabu-posa is that corrected?

**Comment by rambabu-posa** [comment]
@jgperrin Unfortunately I am not able to produce that problem at my end. see below output:


Rambabus-MacBook-Pro:net.jgp.books.spark.ch03 ram$ sbt clean assembly
[info] Loading settings from idea.sbt ...
[info] Loading global plugins from /Users/ram/.sbt/1.0/plugins
[info] Updating {file:/Users/ram/.sbt/1.0/plugins/}global-plugins...
[info] Done updating.
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /Users/ram/SparkInAction2Ed/FinalCode/net.jgp.books.spark.ch03/project
[info] Updating {file:/Users/ram/SparkInAction2Ed/FinalCode/net.jgp.books.spark.ch03/project/}net-jgp-books-spark-ch03-build...
[info] Done updating.
[info] Loading settings from build.sbt ...
[info] Set current project to SparkInAction2-Chapter03 (in build file:/Users/ram/SparkInAction2Ed/FinalCode/net.jgp.books.spark.ch03/)
[success] Total time: 0 s, completed 07-Jun-2021 23:04:25
[info] Updating {file:/Users/ram/SparkInAction2Ed/FinalCode/net.jgp.books.spark.ch03/}net-jgp-books-spark-ch03...
[info] Done updating.
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn] 	* io.netty:netty-all:4.1.47.Final is selected over 4.0.23.Final
[warn] 	    +- org.apache.spark:spark-network-common_2.12:3.0.0   (depends on 4.1.47.Final)
[warn] 	    +- org.apache.spark:spark-core_2.12:3.0.0             (depends on 4.1.47.Final)
[warn] 	    +- org.apache.hadoop:hadoop-hdfs:2.7.4                (depends on 4.0.23.Final)
[warn] 	* com.google.code.findbugs:jsr305:3.0.0 is selected over {3.0.2, 1.3.9}
[warn] 	    +- org.apache.spark:spark-network-common_2.12:3.0.0   (depends on 3.0.0)
[warn] 	    +- org.apache.spark:spark-unsafe_2.12:3.0.0           (depends on 3.0.0)
[warn] 	    +- org.apache.spark:spark-core_2.12:3.0.0             (depends on 3.0.0)
[warn] 	    +- org.apache.hadoop:hadoop-common:2.7.4              (depends on 3.0.0)
[warn] 	    +- com.google.guava:guava:11.0.2                      (depends on 1.3.9)
[warn] 	    +- org.apache.arrow:arrow-memory:0.15.1               (depends on 3.0.2)
[warn] 	    +- com.github.spotbugs:spotbugs-annotations:3.1.9     (depends on 3.0.2)
[warn] 	* com.google.guava:guava:11.0.2 is selected over 16.0.1
[warn] 	    +- org.apache.hadoop:hadoop-yarn-server-nodemanager:2.7.4 (depends on 11.0.2)
[warn] 	    +- org.apache.hadoop:hadoop-yarn-api:2.7.4            (depends on 11.0.2)
[warn] 	    +- org.apache.hadoop:hadoop-yarn-common:2.7.4         (depends on 11.0.2)
[warn] 	    +- org.apache.hadoop:hadoop-hdfs:2.7.4                (depends on 11.0.2)
[warn] 	    +- org.apache.hadoop:hadoop-yarn-client:2.7.4         (depends on 11.0.2)
[warn] 	    +- org.apache.hadoop:hadoop-yarn-server-common:2.7.4  (depends on 11.0.2)
[warn] 	    +- org.apache.curator:curator-framework:2.7.1         (depends on 16.0.1)
[warn] 	    +- org.apache.curator:curator-client:2.7.1            (depends on 16.0.1)
[warn] 	    +- org.apache.hadoop:hadoop-common:2.7.4              (depends on 16.0.1)
[warn] 	    +- org.apache.curator:curator-recipes:2.7.1           (depends on 16.0.1)
[warn] Run 'evicted' to see detailed eviction warnings
[info] Compiling 8 Scala sources and 9 Java sources to /Users/ram/SparkInAction2Ed/FinalCode/net.jgp.books.spark.ch03/target/scala-2.12/classes ...
[info] Done compiling.
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[info] Strategy 'discard' was applied to 338 files (Run the task at debug level to see details)
[info] Strategy 'first' was applied to 30 files (Run the task at debug level to see details)
[info] Packaging /Users/ram/SparkInAction2Ed/FinalCode/net.jgp.books.spark.ch03/target/scala-2.12/SparkInAction2-Chapter03-assembly-1.0.0.jar ...
[info] Done packaging.

**Comment by watchingbird** [comment]
Found this issue while working through the chapter this morning. The problem was resolved for me by making sure I was using Java 8, not 11, during the build.

Although the use of Java 8 is mentioned at the beginning of the book, reiterating its use in the README files for all the labs might be a good idea, as at the end of 2021 and beginning of 2022, a lot of people might be switching between Java versions quite often.
