### ISSUE TITLE
String cannot be cast to scala.runtime.Nothing$ error

### ISSUE THREAD

**Issue by hersonoliveira** [jgperrin/net.jgp.books.spark.ch03#5]
Hi,

I'm trying to run `CsvToDatasetBookToDataframeScalaApp.main()`  and get the following error:
```
2020-05-28 13:25:23.327 -ERROR --- [rker for task 3] ernal.Logging.logError(Logging.scala:94): Exception in task 0.0 in stage 3.0 (TID 3)
java.lang.ClassCastException: java.lang.String cannot be cast to scala.runtime.Nothing$
	at net.jgp.books.spark.ch03.lab320_dataset_books_to_dataframe.CsvToDatasetBookToDataframeScalaApp$BookMapper.call(CsvToDatasetBookToDataframeScalaApp.scala:30)
	at net.jgp.books.spark.ch03.lab320_dataset_books_to_dataframe.CsvToDatasetBookToDataframeScalaApp$BookMapper.call(CsvToDatasetBookToDataframeScalaApp.scala:26)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.mapelements_doConsume_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.deserializetoobject_doConsume_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:726)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:321)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:872)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:872)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:441)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:444)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
I cannot find a workaround for this, any ideas?
Thanks

**Comment by jgperrin** [comment]
@hersonoliveira How did you run it?
@rambabu-posa Can you look into that?

**Comment by jgperrin** [comment]
@hersonoliveira: @rambabu-posa told me he fixed it. Can you confirm?

**Comment by hersonoliveira** [comment]
@jgperrin I run it with Intellij, I didn't try yet using spark-submit

**Comment by jgperrin** [comment]
Try now, @rambabu-posa merged to the master branch his work.

**Comment by hersonoliveira** [comment]
it works now @jgperrin , thanks!
